modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "economycraft"
version = "${version}"
displayName = "EconomyCraft"
authors = "ReaZip"
description = '''
Simple server-side economy and shop mod.
'''

# ---- Minecraft:
[[dependencies.economycraft]]
modId = "minecraft"
type = "required"
versionRange = "[${mcLo},${mcHi})"
ordering = "NONE"
side = "BOTH"

# ---- NeoForge:
[[dependencies.economycraft]]
modId = "neoforge"
type = "required"
versionRange = "[${nfLo},${nfHi})"
ordering = "NONE"
side = "BOTH"

# ---- Architectury:
[[dependencies.economycraft]]
modId = "architectury"
type = "required"
versionRange = "[${archVer},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "economycraft.mixins.json"
