modLoader = "javafml"
loaderVersion = "[9,)"
license = "MIT"

[[mods]]
modId = "economycraft"
version = "${version}"
displayName = "EconomyCraft"
authors = "ReaZip"
description = '''
Simple server-side economy and shop mod.
'''

[[dependencies.economycraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.economycraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.economycraft]]
modId = "architectury"
type = "required"
versionRange = "[17.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "economycraft.mixins.json"
