name: Release NeoForge versions to Modrinth & CurseForge

on:
  workflow_dispatch:

jobs:
  neoforge-1-21:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21
        run: ./gradlew "buildNeoForge_1.21" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.jar

  neoforge-1-21-1:
    runs-on: ubuntu-latest
    needs: neoforge-1-21
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.1
        run: ./gradlew "buildNeoForge_1.21.1" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.1
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.1
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.1.jar

  neoforge-1-21-2:
    runs-on: ubuntu-latest
    needs: neoforge-1-21-1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.2
        run: ./gradlew "buildNeoForge_1.21.2" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.2
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.2
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.2
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.2.jar

  neoforge-1-21-3:
    runs-on: ubuntu-latest
    needs: neoforge-1-21-2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.3
        run: ./gradlew "buildNeoForge_1.21.3" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.3
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.3
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.3
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.3.jar

  neoforge-1-21-4:
    runs-on: ubuntu-latest
    needs: neoforge-1-21-3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.4
        run: ./gradlew "buildNeoForge_1.21.4" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.4
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.4
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.4
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.4.jar

  neoforge-1-21-5:
    runs-on: ubuntu-latest
    needs: neoforge-1-21-4
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.5
        run: ./gradlew "buildNeoForge_1.21.5" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.5
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.5
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.5
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.5.jar

  neoforge-1-21-6:
    runs-on: ubuntu-latest
    needs: neoforge-1-21-5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.6
        run: ./gradlew "buildNeoForge_1.21.6" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.6
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.6
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.6
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.6.jar

  neoforge-1-21-7:
    runs-on: ubuntu-latest
    needs: neoforge-1-21-6
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.7
        run: ./gradlew "buildNeoForge_1.21.7" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.7
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.7
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.7
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.7.jar

  neoforge-1-21-8:
    runs-on: ubuntu-latest
    needs: neoforge-1-21-7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build NeoForge 1.21.8
        run: ./gradlew "buildNeoForge_1.21.8" -Pfilter_platforms=neoforge
      - name: Extract version and changelog
        id: meta
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          VERSION_LINE="$(echo "$COMMIT_MSG" | head -n1)"
          VERSION="$(echo "$VERSION_LINE" | sed 's/Version //')"
          CHANGELOG="$(echo "$COMMIT_MSG" | tail -n +2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Publish NeoForge 1.21.8
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: economycraft
          curseforge-id: 1321557
          modrinth-token: ${{ secrets.MODRINTH_PERSONAL_ACCESS_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_PERSONAL_ACCESS_TOKEN }}
          version: ${{ steps.meta.outputs.version }}
          name: EconomyCraft ${{ steps.meta.outputs.version }} - NeoForge - 1.21.8
          version-type: release
          changelog: ${{ steps.meta.outputs.changelog }}
          game-versions: 1.21.8
          dependencies: |
            architectury-api | depends
          files: |
            neoforge/build/libs/*_1.21.8.jar
